name: Packaging
on:
  push:
    branches:  [ main ]
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    name: Build, test and publish package
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lyska'
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - run: yarn install --frozen-lockfile
      - if: startsWith(github.ref, 'refs/tags/')
        run: yarn pack --filename=babel-plugin-file-shadowing-${{ steps.get_version.outputs.VERSION }}.tgz
      - name: Archive artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: babel-plugin-file-shadowing-${{ steps.get_version.outputs.VERSION }}.tgz
          path: babel-plugin-file-shadowing-${{ steps.get_version.outputs.VERSION }}.tgz
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: babel-plugin-file-shadowing-${{ steps.get_version.outputs.VERSION }}.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}