name: Packaging
on:
  release:
    types: [ published ]
jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    name: Build, test and publish package
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lyska'
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - run: yarn install --frozen-lockfile
      - run: yarn pack --filename=babel-plugin-file-shadowing-${{ steps.get_version.outputs.VERSION }}.tgz
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: babel-plugin-file-shadowing-${{ steps.get_version.outputs.VERSION }}.tgz
          path: babel-plugin-file-shadowing-${{ steps.get_version.outputs.VERSION }}.tgz
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: babel-plugin-file-shadowing-${{ steps.get_version.outputs.VERSION }}.tgz
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}